spring.application.name=mamamia
spring.datasource.url=jdbc:mysql://localhost:3306/mamamia_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
git remote add origin https://github.com/KevSkiu/Pizzeria-MamaMia.git